### ISSUE TITLE
trade button

### ISSUE THREAD

**Issue by Nexiumx** [bouncytorch/trademe#1]
I installed your script, when I write my trade link address and click on the trade button, the transaction does not go through.
I am getting "● Error: Error: Not Logged In" error in the bot. What could be my problem? Can you help me?

**Comment by bouncytorch** [comment]
The source at this time is heavily outdated and downright broken in places, and will soon be upgraded to TypeScript with a few additions and fixes. The development will continue on the `neo` branch until it's ready to merge into main.
